import { AdjustmentsVerticalIcon } from "@heroicons/react/24/solid";
import Head from "next/head";
import { useState } from "react";
import Accordion from "../components/Accordion";
import Alert from "../components/Alert";
import ButtonComp from "../components/ButtonComp";
import Carousel from "../components/Carousel";

export default function Home() {



  const images = [
    'https://images.unsplash.com/photo-1506527240747-720a3e17b910?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1173&q=80',
    'https://images.unsplash.com/photo-1454452176678-c0437432bba6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80',
    'https://images.unsplash.com/photo-1599383885524-8ab14dee8249?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1171&q=80',
    "https://images.unsplash.com/photo-1589730349861-f17e3939c207?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80",
    "https://images.unsplash.com/photo-1533293046890-f1ab3e5e3af9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=735&q=80",
    "https://images.unsplash.com/photo-1626869709532-0d1462483e23?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80",
  ]

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <div className="text-4xl  font-semibold mb">Hallo</div>
        <ButtonComp
          label="click me"
          variant="secondary"
          clickhandler={() => console.log("click")}
          icon={<AdjustmentsVerticalIcon className="w-6 h-6 ml-1" />}
          iconPosition="right"
        />

        <div className="h-[800px]">
          <Carousel images={images} />
        </div>
      </main>
    </>
  );
}
